Update patch set 4
Patch Set 4:

> Patch Set 4: Code-Review-1
> 
> > Patch Set 4:
> > 
> > Looks like the default value is also used for ECDSA. This is a build failure from one of the configs (tftf-l2-fwu/fvp-tspd-tbb-mbedtls-ecdsa-dualroot,fvp-fwu:fvp-tftf.fwu-aemv8a)
> > 
> > NOTICE:  CoT Generation Tool: Built : 14:42:56, Jul 17 2020
> > NOTICE:  Target platform: Dual root of trust
> > ERROR:   '2048' is not a valid key size for 'ecdsa'
> > NOTICE:  Valid sizes are: 
> > Makefile:1211: recipe for target 'certificates' failed
> > make: *** [certificates] Error 1
> > make: Leaving directory '/work/workspace/workspace/tf-worker@10/trusted_firmware'

Hi Zelalem,

I am trying to reproduce the issue locally but my building is failing way before the issue you encounter. Can please help me spotting my build setup problem on the below log?

---------
cd /ext/repos/tf-a-job-local/workspace && mkdir /ext/repos/tf-a-job-local/workspace/ws && BUILD_CONFIG=juno-mbedtls-ecdsa-opteed TEST_CONFIG=juno-mbedtls-ecdsa-opteed:juno-linux.optee RUN_CONFIG=juno-linux.optee TEST_GROUP=tf-l2-boot-tests-juno jenkins_run=0 dont_clean=0 tfa_downloads=/ext/nfs/arm/tf-a import_cc=1 workspace=/ext/repos/tf-a-job-local/workspace/ws nfs_volume=/ext/nfs/arm tf_root=/ext/repos/tf-a-job-local/workspace/trusted-firmware-a tftf_root=/ext/repos/tf-a-job-local/workspace/tf-a-tests CI_ROOT=/ext/repos/tf-a-job-local/workspace/tf-a-ci-scripts MBEDTLS_DIR=/ext/repos/tf-a-job-local/workspace/mbedtls /ext/repos/tf-a-job-local/workspace/tf-a-ci-scripts/job/tf-build-for-lava/build_test.sh

CONFIGURATION: tf-l2-boot-tests-juno/juno-mbedtls-ecdsa-opteed:juno-linux.optee

Trusted Firmware config:

	ARM_ROTPK_LOCATION=devel_ecdsa
	ARM_TSP_RAM_LOCATION=dram
	CREATE_KEYS=1
	CROSS_COMPILE=aarch64-none-elf-
	CSS_USE_SCMI_SDS_DRIVER=1
	GENERATE_COT=1
	KEY_ALG=ecdsa
	PLAT=juno
	ROT_KEY=plat/arm/board/common/rotpk/arm_rotprivk_ecdsa.pem
	SPD=opteed
	TRUSTED_BOARD_BOOT=1

Using existing git clone for tf_root: /ext/repos/tf-a-job-local/workspace/trusted-firmware-a

Chosen fragments:

	juno-linux.optee


##########
Building Trusted Firmware (debug) ...
Fetch: https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.18.0.zip -> /ext/repos/tf-a-job-local/workspace/ws/mbedtls.tar.gz

Build failed! Tail of build log below:
[...]

gcc -c -DVERSION='"v2.3(debug):v2.3-470-gb3385aa08"' -D_GNU_SOURCE -D_XOPEN_SOURCE=700 -Wall -Werror -pedantic -std=c99 -g -O0 -DDEBUG -I../../include/tools_share tbbr_config.c -o tbbr_config.o
  HOSTLD  fiptool
gcc fiptool.o tbbr_config.o -o fiptool -lcrypto

Built fiptool successfully

mkdir -p  "/ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/juno/debug"
mkdir -p  "/ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/juno/debug/libfdt"
mkdir -p  "/ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/juno/debug/lib"
mkdir -p  "/ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/juno/debug/romlib"
aarch64-none-elf-gcc -g -DDEBUG=1 -DENABLE_BACKTRACE=1 -DGIC_EXT_INTID=0 -DJUNO_AARCH32_EL3_RUNTIME=0 -DARM_ROTPK_HASH='"plat/arm/board/common/rotpk/arm_rotpk_ecdsa_sha256.bin"' -DARM_ROTPK_LOCATION_ID=ARM_ROTPK_DEVEL_ECDSA_ID -DARM_COT_tbbr -DARM_BL31_IN_DRAM=0 -DARM_TSP_RAM_LOCATION_ID=ARM_DRAM_ID -DARM_RECOM_STATE_ID_ENC=0 -DARM_DISABLE_TRUSTED_WDOG=0 -DARM_CONFIG_CNTACR=1 -DARM_BL31_IN_DRAM=0 -DARM_PLAT_MT=0 -DARM_XLAT_TABLES_LIB_V1=0 -DARM_LINUX_KERNEL_AS_BL33=0 -DMBEDTLS_SHA256_SMALLER -DARM_CRYPTOCELL_INTEG=0 -DXLAT_TABLES_LIB_V2=1 -DMBEDTLS_CONFIG_FILE="<drivers/auth/mbedtls/mbedtls_config.h>" -DTF_MBEDTLS_KEY_ALG_ID=TF_MBEDTLS_ECDSA -DTF_MBEDTLS_KEY_SIZE -DTF_MBEDTLS_HASH_ALG_ID=TF_MBEDTLS_SHA256 -DTF_MBEDTLS_USE_AES_GCM=0 -DCSS_LOAD_SCP_IMAGES=1 -DCSS_USE_SCMI_SDS_DRIVER=1 -DCSS_NON_SECURE_UART=0 -DA57_ENABLE_NONCACHEABLE_LOAD_FWD=0 -DSKIP_A57_L1_FLUSH_PWR_DWN=1 -DA53_DISABLE_NON_TEMPORAL_HINT=1 -DA57_DISABLE_NON_TEMPORAL_HINT=1 -DWORKAROUND_CVE_2017_5715=1 -DWORKAROUND_CVE_2018_3639=1 -DDYNAMIC_WORKAROUND_CVE_2018_3639=0 -DNEOVERSE_N1_EXTERNAL_LLC=0 -DERRATA_A9_794073=0 -DERRATA_A15_816470=0 -DERRATA_A15_827671=0 -DERRATA_A17_852421=0 -DERRATA_A17_852423=0 -DERRATA_A35_855472=0 -DERRATA_A53_819472=1 -DERRATA_A53_824069=1 -DERRATA_A53_826319=1 -DERRATA_A53_827319=1 -DERRATA_A53_835769=1 -DERRATA_A53_836870=1 -DERRATA_A53_843419=1 -DERRATA_A53_855873=1 -DERRATA_A55_768277=0 -DERRATA_A55_778703=0 -DERRATA_A55_798797=0 -DERRATA_A55_846532=0 -DERRATA_A55_903758=0 -DERRATA_A55_1221012=0 -DERRATA_A57_806969=0 -DERRATA_A57_813419=1 -DERRATA_A57_813420=1 -DERRATA_A57_814670=1 -DERRATA_A57_817169=1 -DERRATA_A57_826974=1 -DERRATA_A57_826977=1 -DERRATA_A57_828024=1 -DERRATA_A57_829520=1 -DERRATA_A57_833471=1 -DERRATA_A57_859972=0 -DERRATA_A72_859971=0 -DERRATA_A73_852427=0 -DERRATA_A73_855423=0 -DERRATA_A75_764081=0 -DERRATA_A75_790748=0 -DERRATA_A76_1073348=0 -DERRATA_A76_1130799=0 -DERRATA_A76_1220197=0 -DERRATA_A76_1257314=0 -DERRATA_A76_1262606=0 -DERRATA_A76_1262888=0 -DERRATA_A76_1275112=0 -DERRATA_A76_1286807=0 -DERRATA_A76_1791580=0 -DERRATA_A76_1800710=0 -DERRATA_A77_1800714=0 -DERRATA_A78_1688305=0 -DERRATA_N1_1043202=0 -DERRATA_N1_1073348=0 -DERRATA_N1_1130799=0 -DERRATA_N1_1165347=0 -DERRATA_N1_1207823=0 -DERRATA_N1_1220197=0 -DERRATA_N1_1257314=0 -DERRATA_N1_1262606=0 -DERRATA_N1_1262888=0 -DERRATA_N1_1275112=0 -DERRATA_N1_1315703=0 -DERRATA_N1_1542419=0 -DERRATA_DSU_798953=0 -DERRATA_DSU_936184=0 -DSTACK_PROTECTOR_ENABLED=0 -DCRASH_REPORTING=1 -DEL3_EXCEPTION_HANDLING=0 -DSDEI_SUPPORT=0 -DALLOW_RO_XLAT_TABLES=0 -DARM_ARCH_MAJOR=8 -DARM_ARCH_MINOR=0 -DCOLD_BOOT_SINGLE_CPU=0 -DCTX_INCLUDE_AARCH32_REGS=1 -DCTX_INCLUDE_FPREGS=0 -DCTX_INCLUDE_PAUTH_REGS=0 -DEL3_EXCEPTION_HANDLING=0 -DCTX_INCLUDE_MTE_REGS=0 -DCTX_INCLUDE_EL2_REGS=0 -DDECRYPTION_SUPPORT_none -DENABLE_AMU=0 -DENABLE_ASSERTIONS=1 -DENABLE_BTI=0 -DENABLE_MPAM_FOR_LOWER_ELS=0 -DENABLE_PAUTH=0 -DENABLE_PIE=0 -DENABLE_PMF=1 -DENABLE_PSCI_STAT=1 -DENABLE_RUNTIME_INSTRUMENTATION=0 -DENABLE_SPE_FOR_LOWER_ELS=1 -DENABLE_SVE_FOR_NS=0 -DENCRYPT_BL31=0 -DENCRYPT_BL32=0 -DERROR_DEPRECATED=0 -DFAULT_INJECTION_SUPPORT=0 -DGICV2_G0_FOR_EL3=0 -DHANDLE_EA_EL3_FIRST=0 -DHW_ASSISTED_COHERENCY=0 -DLOG_LEVEL=40 -DMEASURED_BOOT=0 -DNS_TIMER_SWITCH=1 -DPL011_GENERIC_UART=0 -DPLAT_juno -DPROGRAMMABLE_RESET_ADDRESS=0 -DPSCI_EXTENDED_STATE_ID=0 -DRAS_EXTENSION=0 -DRESET_TO_BL31=0 -DSEPARATE_CODE_AND_RODATA=1 -DSEPARATE_NOBITS_REGION=0 -DRECLAIM_INIT_CODE=0 -DSPD_opteed -DSPIN_ON_BL1_EXIT=0 -DSPM_MM=0 -DSPMD_SPM_AT_SEL2=1 -DTRUSTED_BOARD_BOOT=1 -DUSE_COHERENT_MEM=1 -DUSE_DEBUGFS=0 -DARM_IO_IN_DTB=0 -DSDEI_IN_FCONF=0 -DSEC_INT_DESC_IN_FCONF=0 -DUSE_ROMLIB=0 -DUSE_TBBR_DEFS=1 -DWARMBOOT_ENABLE_DCACHE_EARLY=0 -DBL2_AT_EL3=0 -DBL2_IN_XIP_MEM=0 -DBL2_INV_DCACHE=1 -DUSE_SPINLOCK_CAS=0 -DERRATA_SPECULATIVE_AT=0 -DRAS_TRAP_LOWER_EL_ERR_ACCESS=0 -DCOT_DESC_IN_DTB=0 -DAARCH64 -Iinclude -Iinclude/arch/aarch64 -Iinclude/lib/cpus/aarch64 -Iinclude/lib/el3_runtime/aarch64 -Iplat/arm/board/juno/include -Iinclude/plat/arm/common/aarch64 -Iinclude/plat/arm/css/common/aarch64  -Iinclude/lib/libfdt -Iinclude/lib/libc -Iinclude/lib/libc/aarch64  -I/ext/repos/tf-a-job-local/workspace/ws/mbedtls/include -nostdinc -Werror -Wall -Wmissing-include-dirs -Wunused -Wdisabled-optimization	-Wvla -Wshadow -Wno-unused-parameter -Wredundant-decls -Wunused-but-set-variable -Wmaybe-uninitialized -Wpacked-bitfield-compat -Wshift-overflow=2 -Wlogical-op -Wno-error=deprecated-declarations -Wno-error=cpp -march=armv8-a -mgeneral-regs-only -mstrict-align -mfix-cortex-a53-835769 -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -fno-common -Os -std=gnu99 -fno-omit-frame-pointer -fno-stack-protector  -Wp,-MD,/ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/juno/debug/libfdt/fdt.d -MT /ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/juno/debug/libfdt/fdt.o -MP -c lib/libfdt/fdt.c -o /ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/juno/debug/libfdt/fdt.o
cc1: error: /ext/repos/tf-a-job-local/workspace/ws/mbedtls/include: No such file or directory [-Werror=missing-include-dirs]
cc1: all warnings being treated as errors
make[1]: *** [lib/libfdt/libfdt.mk:20: /ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/juno/debug/libfdt/fdt.o] Error 1
make[1]: Leaving directory '/ext/repos/tf-a-job-local/workspace/trusted-firmware-a'

See /ext/repos/tf-a-job-local/workspace/ws/artefacts/build.log for full output

make: *** [Makefile:95: all] Error 1

Compilation exited abnormally with code 2 at Thu Aug 13 19:24:46
-------------

Patch-set: 4