Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > It would be interesting to see what MISRA thinks about this code. @Andre were you able to runs some MISRA scans?
> 
> Unfortunately, MISRA checks failed as the code didnt compile.
>  
> lib/libc/memset.c: In function 'memset':
> lib/libc/memset.c:13:2: error: unknown type name 'uint64_t'
>    13 |  uint64_t *ptr64;
>       |  ^~~~~~~~
> lib/libc/memset.c:14:2: error: unknown type name 'uint64_t'
>    14 |  uint64_t fill = (unsigned char)val;
>       |  ^~~~~~~~
> lib/libc/memset.c:21:11: error: 'uintptr_t' undeclared (first use in this function)
>    21 |  while (((uintptr_t)ptr & 7)) {
>       |           ^~~~~~~~~
> lib/libc/memset.c:21:11: note: each undeclared identifier is reported only once for each function it appears in
> lib/libc/memset.c:21:21: error: expected ')' before 'ptr'
>    21 |  while (((uintptr_t)ptr & 7)) {
>       |         ~           ^~~
>       |                     )
> lib/libc/memset.c:30:15: error: left shift count >= width of type [-Werror=shift-count-overflow]
>    30 |  fill |= fill << 32;

Doh! My sincere apologies for that! I was so occupied with my unit testing, that I forgot to sync the result back into the TF-A tree properly (it's missing stdint.h).
Fixed that and also the brackets situation and will post a v2 ASAP.

Patch-set: 1
Reviewer: Gerrit User 1000118 <1000118@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>