Update patch set 4
Patch Set 4:

Hi Bai,

> You mean the includes ordering issue? I think I have sorted the includes in three groups, not sure why CI reports such error. Can you give me some hints? Any local checkpatch tool available for such error check?

Yes that's what I meant. That being said, I am looking closer at the script's output and I think it might report some false positives in this specific instance... I'll look more into it and let you know. BTW, this script is internal to Arm right now so I am afraid you won't be able to run it on your local machine.

I also meant that the issues reported by the checkpatch.pl script need to be fixed. It reports some warnings, which you may optionally fix, but also reports some errors, which must be fixed. Copying them here for reference:

 plat/imx/imx8m/imx8mn/gpc.c:91: ERROR: spaces required around that '=' (ctx:WxV)
 +	for(i =0; i < 103; i++)
 	      ^

plat/imx/imx8m/imx8mn/gpc.c:91: ERROR: space required before the open parenthesis '('
 +	for(i =0; i < 103; i++)

Patch-set: 4
Reviewer: Gerrit User 1000043 <1000043@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>