Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > Patch Set 5:
> > 
> > > Patch Set 5:
> > > 
> > > > Patch Set 5:
> > > > 
> > > > > Patch Set 5:
> > > > > 
> > > > > > Patch Set 4:
> > > > > > 
> > > > > > (3 comments)
> > > > > > 
> > > > > > > Patch Set 4:
> > > > > > > 
> > > > > > > (3 comments)
> > > > > > > 
> > > > > > > > Patch Set 1:
> > > > > > > > 
> > > > > > > > > Patch Set 1:
> > > > > > > > > 
> > > > > > > > > > Patch Set 1:
> > > > > > > > > > 
> > > > > > > > > > I am unsure if uint64_t is supposed to be long or long long for aarch64.
> > > > > > > > > > 
> > > > > > > > > > But, the move to inttypes.h should be done for fixed width types for portability reasons and proper printf format specifiers.
> > > > > > > > > > Perhaps I should introduce that inttypes.h first and then have the stdint.h change in a follow on commit?
> > > > > > > > > 
> > > > > > > > > unsigned long on aarch64 gcc is 64 bits. unsigned long long is usually not used on aarch64.
> > > > > > > > 
> > > > > > > > great, thanks for clarification.
> > > > > > > 
> > > > > > > Both long and long long are 64-bit values in Aarch64.
> > > > > > > What made you come to conclusion that long long is not used on Aarch64? What about the Aarch32/64 common headers and sources which use this type?
> > > > > > > Please explain what was the problem with using existing "ll" notation for long long numbers and replacing it with new defined PRI?64. There are also other added definitions of PRI?8/16/32, are you going to change all the code to use them and would it be practical and provide more readability in your opinion?
> > > > > > 
> > > > > > The problem with existing "ll" notation is that standard uint64_t is a long on Aarch64 (and other 64-bit architectures) in gcc compiler stdint.h.  ATF redefines it's own stdint.h with uint64_t as "long long".  This is correct for 32-bit architectures but is not how uint64_t is defined for 64-bit architectures.  Creating an incompatible stdint.h in ATF creates a few problems:
> > > > > > 
> > > > > > 1) Code is not portable.  Code with printf format specifiers for 64_t types will not recompile when ported to/from ATF.
> > > > > > 2) Static analysis tools get confused.  We get parse errors when running coverity scan analysis on ATF due to a different type of stdint type for uint64_t.
> > > > > > 
> > > > > > To solve both of these problems the solution is to use the proper printf format specifiers for 64-bit fixed width types.  Technically speaking, PRI?8/16/32 should be used for other stdint.h types as well but it is not needed for aarch32/64 usage.  I added the proper definitions for such format specifiers because they should be available for people to use.  I'm not about to change all the 8/16/32 to use such types as the current printf format specifiers are compatible between aarch32/64.
> > > > > > 
> > > > > > I agree it is not more readable to use the proper printf format specifiers for fixed width types but this is how stdio.h, stdint.h, and inttypes.h work in C if you want to compile the code for 32 and 64 bit architectures.
> > > > > > 
> > > > > > Redefining uint64_t to long long in ATF (or any other type to something different that what is in stdint.h in compiler) is not the way to go as it creates the problems described above.  It seems to be a convenience simply to allow code to use 0x%llx on 32 and 64 bit architectures.
> > > > > 
> > > > > What happens if you change TF-A stdint.h:
> > > > > #ifdef __aarch64__
> > > > > typedef unsigned long uint64_t;
> > > > > typedef long uint64_t;
> > > > > #endif
> > > > > ?
> > > > 
> > > > I don't understand the question but I don't think it would compile.
> > > > Why would you define uint64_t to an unsigned long and then a long?
> > > > 
> > > > And what are you trying to ask?
> > > 
> > > It was a typo, should be:
> > > typedef long int64_t;
> > > This causes 
> > > error: format '%llx' expects argument of type 'long long unsigned int', but argument 2 has type 'uint64_t' {aka 'long unsigned int'}
> > 
> > Alexei, correct, the used of %llx is not the correct printf format specifier to use for uint16_t.  The printf format specifiers for fixed width types defined in stdint.h are in inttypes.h  PRIx64 is the correct specifier for uint16_t and int64_t types in your example.  See https://en.wikipedia.org/wiki/C_data_types#Printf_and_scanf_format_specifiers
> 
> Scott why do you mention "uint16_t" here?
> This change effects all TF-A common & platforms' code, so I'd suggest to discuss your proposal on the mailing list.

It's a TYPO: uint16_t should be uint64_t.

I can send if a message to the mailing list if that is required.

Patch-set: 5
Reviewer: Gerrit User 1000319 <1000319@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>