Update patch set 2
Patch Set 2: -Allow-CI

Following static check failures 


=================================================================================
Currently, explicitly initializing static variables causes a failure and i am looking into it, but could you please fix it in current patch.

drivers/marvell/mochi/cp110_setup.c:389: ERROR: do not initialise statics to false
+	static bool done = false;


==================================================================================
****** Order of includes on the last patch(es) ******

Result : FAILURE

Checking files modified between patches origin/master and HEAD...
6510edc41:drivers/rambus/trng_ip_76.c: ['Project includes not in order. Include order
    should be common/debug.h, drivers/delay_timer.h, drivers/rambus/trng_ip_76.h,
    lib/mmio.h, lib/spinlock.h, lib/utils.h']

2fb5ed473:plat/qemu/qemu_sbsa/sbsa_pm.c: ['assert.h should be in system group, at
    the top']

2fbb60642:fdts/stm32mp157c-lxa-mc1.dts: ['Project includes not in order. Include order
    should be stm32mp15-ddr3-1x4Gb-1066-binG.dtsi, stm32mp157.dtsi, stm32mp15xc.dtsi,
    stm32mp15xx-osd32.dtsi, stm32mp15xxac-pinctrl.dtsi']

2fbb60642:fdts/stm32mp15xx-osd32.dtsi: ['Project includes not in order. Include order
    should be dt-bindings/clock/stm32mp1-clksrc.h, stm32mp15-pinctrl.dtsi']

618522eb2:drivers/renesas/rzg/pfc/G2M/pfc_init_g2m.c: ['pfc_regs.h should be in project
    group, after system group']

618522eb2:drivers/renesas/rzg/pfc/pfc_init.c: ['Project includes not in order. Include
    order should be G2M/pfc_init_g2m.h, G2M/pfc_init_g2m.h, common/debug.h, lib/mmio.h']

f4db9216f:drivers/renesas/rzg/qos/G2M/qos_init_g2m_v10.c: ['Project includes not in
    order. Include order should be ../qos_common.h, common/debug.h, lib/mmio.h, qos_init_g2m_v10.h,
    qos_init_g2m_v10_mstat.h, qos_reg.h']

f4db9216f:drivers/renesas/rzg/qos/G2M/qos_init_g2m_v11.c: ['Project includes not in
    order. Include order should be ../qos_common.h, common/debug.h, lib/mmio.h, qos_init_g2m_v11.h,
    qos_init_g2m_v11_mstat195.h, qos_init_g2m_v11_mstat390.h, qos_init_g2m_v11_qoswt195.h,
    qos_init_g2m_v11_qoswt390.h, qos_reg.h']

f4db9216f:drivers/renesas/rzg/qos/G2M/qos_init_g2m_v30.c: ['Project includes not in
    order. Include order should be ../qos_common.h, common/debug.h, lib/mmio.h, qos_init_g2m_v30.h,
    qos_init_g2m_v30_mstat195.h, qos_init_g2m_v30_mstat390.h, qos_init_g2m_v30_qoswt195.h,
    qos_init_g2m_v30_qoswt390.h, qos_reg.h']

f4db9216f:drivers/renesas/rzg/qos/qos_init.c: ['Project includes not in order. Include
    order should be G2M/qos_init_g2m_v10.h, G2M/qos_init_g2m_v10.h, G2M/qos_init_g2m_v11.h,
    G2M/qos_init_g2m_v11.h, G2M/qos_init_g2m_v30.h, G2M/qos_init_g2m_v30.h, common/debug.h,
    lib/mmio.h, qos_common.h, qos_init.h, qos_reg.h']

ed4fde312:drivers/renesas/rzg/ddr/ddr_b/boot_init_dram.c: ['boot_init_dram_config.c
    should be in project group, after system group']

Patch-set: 2
Reviewer: Gerrit User 1000102 <1000102@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>
Label: Allow-CI=0