Update patch set 17
Patch Set 17:

Getting build fails in this patch due to some undefines:
gcc -c -DVERSION='"v2.4(debug):31a78f7"' -D_GNU_SOURCE -D_XOPEN_SOURCE=700 -Wall -Werror -pedantic -std=c99 -g -O0 -DDEBUG -I../../include/tools_share fiptool.c -o fiptool.o
14:14:01   HOSTCC  tbbr_config.c
14:14:01 gcc -c -DVERSION='"v2.4(debug):31a78f7"' -D_GNU_SOURCE -D_XOPEN_SOURCE=700 -Wall -Werror -pedantic -std=c99 -g -O0 -DDEBUG -I../../include/tools_share tbbr_config.c -o tbbr_config.o
14:14:01 tbbr_config.c:73:11: error: 'UUID_DDR_IMEM_UDIMM_1D' undeclared here (not in a function)
14:14:01    .uuid = UUID_DDR_IMEM_UDIMM_1D,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~
14:14:01 tbbr_config.c:78:11: error: 'UUID_DDR_IMEM_UDIMM_2D' undeclared here (not in a function); did you mean 'UUID_DDR_IMEM_UDIMM_1D'?
14:14:01    .uuid = UUID_DDR_IMEM_UDIMM_2D,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_DDR_IMEM_UDIMM_1D
14:14:01 tbbr_config.c:83:11: error: 'UUID_DDR_DMEM_UDIMM_1D' undeclared here (not in a function); did you mean 'UUID_DDR_IMEM_UDIMM_1D'?
14:14:01    .uuid = UUID_DDR_DMEM_UDIMM_1D,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_DDR_IMEM_UDIMM_1D
14:14:01 tbbr_config.c:88:11: error: 'UUID_DDR_DMEM_UDIMM_2D' undeclared here (not in a function); did you mean 'UUID_DDR_DMEM_UDIMM_1D'?
14:14:01    .uuid = UUID_DDR_DMEM_UDIMM_2D,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_DDR_DMEM_UDIMM_1D
14:14:01 tbbr_config.c:93:11: error: 'UUID_DDR_IMEM_RDIMM_1D' undeclared here (not in a function); did you mean 'UUID_DDR_IMEM_UDIMM_1D'?
14:14:01    .uuid = UUID_DDR_IMEM_RDIMM_1D,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_DDR_IMEM_UDIMM_1D
14:14:01 tbbr_config.c:98:11: error: 'UUID_DDR_IMEM_RDIMM_2D' undeclared here (not in a function); did you mean 'UUID_DDR_IMEM_RDIMM_1D'?
14:14:01    .uuid = UUID_DDR_IMEM_RDIMM_2D,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_DDR_IMEM_RDIMM_1D
14:14:01 tbbr_config.c:103:11: error: 'UUID_DDR_DMEM_RDIMM_1D' undeclared here (not in a function); did you mean 'UUID_DDR_IMEM_RDIMM_1D'?
14:14:01    .uuid = UUID_DDR_DMEM_RDIMM_1D,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_DDR_IMEM_RDIMM_1D
14:14:01 tbbr_config.c:108:11: error: 'UUID_DDR_DMEM_RDIMM_2D' undeclared here (not in a function); did you mean 'UUID_DDR_DMEM_RDIMM_1D'?
14:14:01    .uuid = UUID_DDR_DMEM_RDIMM_2D,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_DDR_DMEM_RDIMM_1D
14:14:01 tbbr_config.c:113:11: error: 'UUID_FUSE_PROV' undeclared here (not in a function)
14:14:01    .uuid = UUID_FUSE_PROV,
14:14:01            ^~~~~~~~~~~~~~
14:14:01 tbbr_config.c:118:11: error: 'UUID_FUSE_UP' undeclared here (not in a function); did you mean 'UUID_FUSE_PROV'?
14:14:01    .uuid = UUID_FUSE_UP,
14:14:01            ^~~~~~~~~~~~
14:14:01            UUID_FUSE_PROV
14:14:01 tbbr_config.c:186:11: error: 'UUID_DDR_FW_KEY_CERT' undeclared here (not in a function); did you mean 'UUID_SOC_FW_KEY_CERT'?
14:14:01    .uuid = UUID_DDR_FW_KEY_CERT,
14:14:01            ^~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_SOC_FW_KEY_CERT
14:14:01 tbbr_config.c:228:11: error: 'UUID_DDR_UDIMM_FW_CONTENT_CERT' undeclared here (not in a function); did you mean 'UUID_TRUSTED_OS_FW_CONTENT_CERT'?
14:14:01    .uuid = UUID_DDR_UDIMM_FW_CONTENT_CERT,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_TRUSTED_OS_FW_CONTENT_CERT
14:14:01 tbbr_config.c:233:11: error: 'UUID_DDR_RDIMM_FW_CONTENT_CERT' undeclared here (not in a function); did you mean 'UUID_DDR_UDIMM_FW_CONTENT_CERT'?
14:14:01    .uuid = UUID_DDR_RDIMM_FW_CONTENT_CERT,
14:14:01            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:14:01            UUID_DDR_UDIMM_FW_CONTENT_CERT
14:14:01 Makefile:61: recipe for target 'tbbr_config.o' failed
14:14:01 make[1]: *** [tbbr_config.o] Error 1
14:14:01 Makefile:1316: recipe for target 'tools/fiptool/fiptool' failed
14:14:01 make: *** [tools/fiptool/fiptool] Error 2

Please fix and we can rerun...

Patch-set: 17
Reviewer: Gerrit User 1000124 <1000124@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>