Update patch set 8
Patch Set 8:

HI Julius,
There is a build error for rk3288 platform. 

```
11:27:22 plat/rockchip/common/sp_min_plat_setup.c:43:6: error: conflicting types for 'params_early_setup'
11:27:22  void params_early_setup(void *plat_param_from_bl2)
11:27:22       ^~~~~~~~~~~~~~~~~~
11:27:22 In file included from plat/rockchip/common/sp_min_plat_setup.c:19:0:
11:27:22 plat/rockchip/common/include/plat_private.h:98:6: note: previous declaration of 'params_early_setup' was here
11:27:22  void params_early_setup(u_register_t plat_params_from_bl2);
11:27:22       ^~~~~~~~~~~~~~~~~~
11:27:22 Makefile:809: recipe for target 'build/rk3288/debug/bl32/sp_min_plat_setup.o' failed
11:27:22 make: *** [build/rk3288/debug/bl32/sp_min_plat_setup.o] Error 1
11:27:22 
```

The sp_min file has to be fixed up for the change in function prototype.

Patch-set: 8