Update patch set 19
Patch Set 19:

> Patch Set 19: Verified-1
> 
> Build Failed 
> 
> https://jenkins.oss.arm.com/job/tf-gerrit-tforg-l1/3681/ : This Jenkins server is not publicly accessible. A core maintainer will let you know if this CI failure is blocking the merge of this patch.

Looks like some undefines?  Compile fails in test run:
src/tbbr/tbb_ext.c:327:10: error: ‘DDR_FW_CONTENT_CERT_PK_OID’ undeclared here (not in a function); did you mean ‘DDR_FW_CONTENT_CERT_PK_EXT’?
   .oid = DDR_FW_CONTENT_CERT_PK_OID,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          DDR_FW_CONTENT_CERT_PK_EXT
src/tbbr/tbb_ext.c:335:10: error: ‘DDR_IMEM_UDIMM_1D_HASH_OID’ undeclared here (not in a function); did you mean ‘DDR_IMEM_UDIMM_1D_HASH_EXT’?
   .oid = DDR_IMEM_UDIMM_1D_HASH_OID,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          DDR_IMEM_UDIMM_1D_HASH_EXT
src/tbbr/tbb_ext.c:344:10: error: ‘DDR_IMEM_UDIMM_2D_HASH_OID’ undeclared here (not in a function); did you mean ‘DDR_IMEM_UDIMM_1D_HASH_OID’?
   .oid = DDR_IMEM_UDIMM_2D_HASH_OID,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          DDR_IMEM_UDIMM_1D_HASH_OID
src/tbbr/tbb_ext.c:353:10: error: ‘DDR_DMEM_UDIMM_1D_HASH_OID’ undeclared here (not in a function); did you mean ‘DDR_IMEM_UDIMM_1D_HASH_OID’?
   .oid = DDR_DMEM_UDIMM_1D_HASH_OID,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          DDR_IMEM_UDIMM_1D_HASH_OID
src/tbbr/tbb_ext.c:362:10: error: ‘DDR_DMEM_UDIMM_2D_HASH_OID’ undeclared here (not in a function); did you mean ‘DDR_DMEM_UDIMM_1D_HASH_OID’?
   .oid = DDR_DMEM_UDIMM_2D_HASH_OID,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          DDR_DMEM_UDIMM_1D_HASH_OID
src/tbbr/tbb_ext.c:371:10: error: ‘DDR_IMEM_RDIMM_1D_HASH_OID’ undeclared here (not in a function); did you mean ‘DDR_IMEM_UDIMM_1D_HASH_OID’?
   .oid = DDR_IMEM_RDIMM_1D_HASH_OID,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          DDR_IMEM_UDIMM_1D_HASH_OID
src/tbbr/tbb_ext.c:380:10: error: ‘DDR_IMEM_RDIMM_2D_HASH_OID’ undeclared here (not in a function); did you mean ‘DDR_IMEM_RDIMM_1D_HASH_OID’?
   .oid = DDR_IMEM_RDIMM_2D_HASH_OID,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          DDR_IMEM_RDIMM_1D_HASH_OID
src/tbbr/tbb_ext.c:389:10: error: ‘DDR_DMEM_RDIMM_1D_HASH_OID’ undeclared here (not in a function); did you mean ‘DDR_IMEM_RDIMM_1D_HASH_OID’?
   .oid = DDR_DMEM_RDIMM_1D_HASH_OID,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          DDR_IMEM_RDIMM_1D_HASH_OID
src/tbbr/tbb_ext.c:398:10: error: ‘DDR_DMEM_RDIMM_2D_HASH_OID’ undeclared here (not in a function); did you mean ‘DDR_DMEM_RDIMM_1D_HASH_OID’?
   .oid = DDR_DMEM_RDIMM_2D_HASH_OID,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          DDR_DMEM_RDIMM_1D_HASH_OID

Possibly missing platform_oid.h?

Patch-set: 19
Reviewer: Gerrit User 1000124 <1000124@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>