Update patch set 2
Patch Set 2: Code-Review-2

It looks like there are build errors on many platforms with this patch. CI output as follows:

10:55:59 In file included from drivers/delay_timer/delay_timer.c:11:
10:55:59 include/drivers/delay_timer.h: In function 'arm_cnt_us2cnt':
10:55:59 include/drivers/delay_timer.h:28:35: error: implicit declaration of function 'read_cntfrq_el0' [-Werror=implicit-function-declaration]
10:55:59   return ((uint64_t)us * (uint64_t)read_cntfrq_el0()) / 1000000ULL;
10:55:59                                    ^~~~~~~~~~~~~~~
10:55:59 include/drivers/delay_timer.h: In function 'timeout_init_us':
10:55:59 include/drivers/delay_timer.h:33:9: error: implicit declaration of function 'read_cntpct_el0' [-Werror=implicit-function-declaration]
10:55:59   return read_cntpct_el0() + arm_cnt_us2cnt(us);
10:55:59          ^~~~~~~~~~~~~~~
10:55:59 cc1: all warnings being treated as errors
10:55:59 Makefile:817: recipe for target 'build/fvp/debug/bl1/delay_timer.o' failed
10:55:59 make: *** [build/fvp/debug/bl1/delay_timer.o] Error 1

Seems that read_cntpct_el0 is not defined so it could be as simple as including arch_helpers.h, but I haven't checked for sure. You can build the FVP platform target to verify this. Please resubmit your patch with the appropriate fix.

Patch-set: 2
Label: Code-Review=-2