Update patch set 1
Patch Set 1: -Allow-CI

Hi Imre,
       There are some CI fails unrelated to your patch. (tegra platforms fails to build due to changes in console framwework.) 
However, two tests fail with the following message which I feel is relevant to your patch:

  Error: /work/workspace/workspace/tf-worker@2/trusted_firmware/fdts/fvp-base-gicv3-psci-aarch32-common.dtsi:7.1-9 syntax error
 FATAL ERROR: Unable to parse input tree
 Build step 'Conditional step (single)' marked build as failure

Patch-set: 1
Reviewer: Gerrit User 1000098 <1000098@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>
Label: Allow-CI=0