Update patch set 3
Patch Set 3:

> Patch Set 3: Verified-2
> 
> Build Failed 
> 
> https://jenkins.oss.arm.com/job/tf-gerrit-tforg-l2/801/ : This Jenkins server is not publicly accessible. A core maintainer will let you know if this CI failure is blocking the merge of this patch.

There are a few platform build failures which are worth fixing

FVP aarch32:

16:39:49 lib/semihosting/semihosting.c: In function 'semihosting_exit':
16:39:49 lib/semihosting/semihosting.c:228:41: error: passing argument 2 of 'semihosting_call' makes pointer from integer without a cast [-Werror=int-conversion]
16:39:49   228 |  semihosting_call(SEMIHOSTING_SYS_EXIT, reason);
16:39:49       |                                         ^~~~~~
16:39:49       |                                         |
16:39:49       |                                         uint32_t {aka unsigned int}
16:39:49 lib/semihosting/semihosting.c:18:10: note: expected 'void *' but argument is of type 'uint32_t' {aka 'unsigned int'}
16:39:49    18 |    void *system_block_address);
16:39:49       |    ~~~~~~^~~~~~~~~~~~~~~~~~~~
16:39:49 cc1: all warnings being treated as errors
16:39:49 Makefile:878: recipe for target 'build/qemu/debug/bl1/semihosting.o' failed

qemu sbsa:

16:39:56 plat/qemu/common/qemu_bl2_setup.c: In function 'update_dt':
16:39:56 plat/qemu/common/qemu_bl2_setup.c:54:33: error: 'ARM_PRELOADED_DTB_BASE' undeclared (first use in this function); did you mean 'PRELOADED_BL33_BASE'?
16:39:56    54 |  void *fdt = (void *)(uintptr_t)ARM_PRELOADED_DTB_BASE;
16:39:56       |                                 ^~~~~~~~~~~~~~~~~~~~~~
16:39:56       |                                 PRELOADED_BL33_BASE
16:39:56 plat/qemu/common/qemu_bl2_setup.c:54:33: note: each undeclared identifier is reported only once for each function it appears in
16:39:56 Makefile:886: recipe for target 'build/qemu_sbsa/debug/bl2/qemu_bl2_setup.o' failed
16:39:56 make: *** [build/qemu_sbsa/debug/bl2/qemu_bl2_setup.o] Error 1

Thanks, Olivier.

Patch-set: 3