Update patch set 6
Patch Set 6:

> Patch Set 5:
> 
> plat/mediatek/mt8183/drivers/spm/spm.c:329:13: error: ‘spm_code_swapping’ defined but not used [-Werror=unused-function]
>  static void spm_code_swapping(void)
>              ^~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> Makefile:799: recipe for target 'build/mt8183/debug/bl31/spm.o' failed
> make: *** [build/mt8183/debug/bl31/spm.o] Error 1

Updated in
https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/1805/4..5/plat/mediatek/mt8183/drivers/spm/spm.c#b329

Patch-set: 6
Reviewer: Gerrit User 1000123 <1000123@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>
Label: Code-Review=0