Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> (1 comment)

Drafted the following two changes:
1. following change in Gerrit review request #6146:

drivers/nxp/auth/tbbr/tbbr_cot.c
@@ -8,8 +8,8 @@
 
 #include <stddef.h>
 
-#include <drivers/auth/auth_mod.h>
 #include <drivers/auth/mbedtls/mbedtls_config.h>
+#include <drivers/auth/auth_mod.h>the source file inclusion, 


2. following change in Gerrit review request #6157:

--- a/plat/nxp/common/tbbr/tbbr.mk
+++ b/plat/nxp/common/tbbr/tbbr.mk
@@ -136,11 +136,11 @@ endif #MBEDTLS_DIR
 PLAT_INCLUDES          +=      -Iinclude/common/tbbr
 
 # Generic files for authentication framework
-TBBR_SOURCES           +=      drivers/auth/auth_mod.c         \
+TBBR_SOURCES           +=      ${PLAT_TBBR_SOURCES}            \
+                               drivers/auth/auth_mod.c         \
                                drivers/auth/crypto_mod.c       \
                                drivers/auth/img_parser_mod.c   \
-                               plat/common/tbbr/plat_tbbr.c    \
-                               ${PLAT_TBBR_SOURCES}
+                               plat/common/tbbr/plat_tbbr.c

Observation in the compilation log:
A. 
  CC      drivers/nxp/auth/tbbr/tbbr_cot.c
In file included from include/drivers/auth/auth_mod.h:12:0,
                 from drivers/nxp/auth/tbbr/tbbr_cot.c:12:
include/common/tbbr/cot_def.h:41:2: error: #error "294 294 294 294"
 #error "294 294 294 294"                                           // This is fixed by above solution.

B.
  CC      drivers/auth/auth_mod.c
In file included from drivers/auth/auth_mod.c:14:0:
include/common/tbbr/cot_def.h:50:2: error: #error "919191919191191"
 #error "919191919191191"                                          // Here, it is still an issue.


Can you guide me on this with better way?

Thanks.

Patch-set: 2