Update patch set 4
Patch Set 4:

> Patch Set 4: -Allow-CI
> 
> Please fix Static check failure, failure can be in any patch below this patch. 
> 
> ****** Order of includes on the last patch(es) ******
> 
> Result : FAILURE
> 
> Checking files modified between patches origin/master and HEAD...
> 970083719:drivers/renesas/rcar/iic_dvfs/iic_dvfs.c: ['iic_dvfs.h should be in project
>     group, after system group']

I have just reordered the header files as per TF-A coding standard. so i believe it should be ok??

> c01b6052b:drivers/renesas/rcar/auth/auth_mod.c: ['rom_api.h should be in project group,
>     after system group']

I have just reordered the header files as per TF-A coding standard. so i believe it should be ok??

> 
> ****** Coding style on current patch ******
> 
> Result : FAILURE
> drivers/renesas/rcar/iic_dvfs/iic_dvfs.c:418: ERROR: need consistent spacing around '*' (ctx:WxV)
> +IIC_DVFS_FUNC(change_send_to_receive, DVFS_STATE_T *state, uint32_t *err)

I believe checkpatch won't work well with typedef's. DVFS_STATE_T is typedef and actually the original file has the below errors[1]. The fix is, i need to remove the typedef's for DVFS_STATE_T and use directly the enum. But as per [2], Existing typedefs will be retained for compatibility. 

Since it is existing typedef, do you want me to keep as it is or fix the same? Please let me know. 

[2]https://trustedfirmware-a.readthedocs.io/en/latest/process/coding-style.html#coding-style
"Some TF definitions use both a struct/enum name and a typedef name. This is discouraged for new definitions as it makes it difficult for TF to comply with MISRA rule 8.3, which states that “All declarations of an object or function shall use the same names and type qualifiers”.

The Linux coding standards also discourage new typedefs and checkpatch emits a warning for this.

Existing typedefs will be retained for compatibility."

[1]
---
drivers/renesas/temp/iic_dvfs/iic_dvfs.c:97: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(check_error, DVFS_STATE_T *state, uint32_t *err, uint8_t mode)
                                         ^

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:256: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(write_addr, DVFS_STATE_T *state, uint32_t *err, uint8_t reg_addr)
                                        ^

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:279: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(write_data, DVFS_STATE_T *state, uint32_t *err, uint8_t reg_data)
                                        ^

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:302: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(stop, DVFS_STATE_T *state, uint32_t *err)
                                  ^

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:342: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(write_reg_addr_read, DVFS_STATE_T *state, uint32_t *err,
                                                 ^

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:366: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(retransmit, DVFS_STATE_T *state, uint32_t *err)
                                        ^

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:392: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(set_slave_read, DVFS_STATE_T *state, uint32_t *err,
                                            ^

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:413: WARNING: 'RECIEVE' may be misspelled - perhaps 'RECEIVE'?
+	*state = DVFS_CHANGE_SEND_TO_RECIEVE;

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:418: WARNING: 'recieve' may be misspelled - perhaps 'receive'?
+IIC_DVFS_FUNC(change_send_to_recieve, DVFS_STATE_T *state, uint32_t *err)

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:418: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(change_send_to_recieve, DVFS_STATE_T *state, uint32_t *err)
                                                    ^

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:441: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(stop_read, DVFS_STATE_T *state, uint32_t *err)
                                       ^

drivers/renesas/temp/iic_dvfs/iic_dvfs.c:467: ERROR: need consistent spacing around '*' (ctx:WxV)
+IIC_DVFS_FUNC(read, DVFS_STATE_T *state, uint8_t *reg_data)
                                  ^

Patch-set: 4