Update patch set 5
Patch Set 5:

The only 2 CI failures because of sc7180 build problem:
In file included from plat/qti/common/src/qti_stack_protector.c:12:
plat/qti/common/inc/qti_rng.h:10:10: fatal error: stdinit.h: No such file or directory
   10 | #include <stdinit.h>
      |          ^~~~~~~~~~~

Patch-set: 5
Reviewer: Gerrit User 1000105 <1000105@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>