Update patch set 3
Patch Set 3:

> Patch Set 3: -Allow-CI
> 
> > Patch Set 3: Verified-2
> > 
> > Build Failed 
> > 
> > https://jenkins.oss.arm.com/job/tf-gerrit-tforg-l2/1204/ : This Jenkins server is not publicly accessible. A core maintainer will let you know if this CI failure is blocking the merge of this patch.
> 
> Two more failures at multiple places
> 1. lib/fconf/fconf_tbbr_getter.c: In function 'fconf_populate_tbbr_dyn_config':
> lib/fconf/fconf_tbbr_getter.c:58:38: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
>    58 |  tbbr_dyn_config.mbedtls_heap_addr = (void *)val64;
>       |                                      ^
> cc1: all warnings being treated as errors
> Makefile:1035: recipe for target 'build/fvp/debug/bl1/fconf_tbbr_getter.o' failed
> make: *** [build/fvp/debug/bl1/fconf_tbbr_getter.o] Error 1

Yeah, found this already. Actually another mainline bug: Here we read a 64-bit value into a "void *", which is 32-bits only in AArch32. Overwrites whatever is in the next 4 bytes.
Mainline compiles fine, but is broken, with this series you get the build error.


> ==========================================================================================
> 
> 2. aarch64-none-elf-ar -rc ../.././build/fvp/debug/lib/libwrappers.a ../.././build/fvp/debug/libwrapper/jmpvar.o ../.././build/fvp/debug/libwrapper/rom_lib_init.o ../.././build/fvp/debug/libwrapper/fdt_getprop_namelen.o ../.././build/fvp/debug/libwrapper/fdt_setprop_inplace.o ../.././build/fvp/debug/libwrapper/fdt_check_header.o ../.././build/fvp/debug/libwrapper/fdt_node_offset_by_compatible.o ../.././build/fvp/debug/libwrapper/fdt_setprop_inplace_namelen_partial.o ../.././build/fvp/debug/libwrapper/fdt_first_subnode.o ../.././build/fvp/debug/libwrapper/fdt_next_subnode.o ../.././build/fvp/debug/libwrapper/fdt_path_offset.o ../.././build/fvp/debug/libwrapper/fdt_subnode_offset.o ../.././build/fvp/debug/libwrapper/mbedtls_asn1_get_alg.o ../.././build/fvp/debug/libwrapper/mbedtls_asn1_get_alg_null.o ../.././build/fvp/debug/libwrapper/mbedtls_asn1_get_bitstring_null.o ../.././build/fvp/debug/libwrapper/mbedtls_asn1_get_bool.o ../.././build/fvp/debug/libwrapper/mbedtls_asn1_get_int.o ../.././build/fvp/debug/libwrapper/mbedtls_asn1_get_tag.o ../.././build/fvp/debug/libwrapper/mbedtls_free.o ../.././build/fvp/debug/libwrapper/mbedtls_md.o ../.././build/fvp/debug/libwrapper/mbedtls_md_get_size.o ../.././build/fvp/debug/libwrapper/mbedtls_memory_buffer_alloc_init.o ../.././build/fvp/debug/libwrapper/mbedtls_oid_get_md_alg.o ../.././build/fvp/debug/libwrapper/mbedtls_oid_get_numeric_string.o ../.././build/fvp/debug/libwrapper/mbedtls_oid_get_pk_alg.o ../.././build/fvp/debug/libwrapper/mbedtls_oid_get_sig_alg.o ../.././build/fvp/debug/libwrapper/mbedtls_pk_free.o ../.././build/fvp/debug/libwrapper/mbedtls_pk_init.o ../.././build/fvp/debug/libwrapper/mbedtls_pk_parse_subpubkey.o ../.././build/fvp/debug/libwrapper/mbedtls_pk_verify_ext.o ../.././build/fvp/debug/libwrapper/mbedtls_platform_set_snprintf.o ../.././build/fvp/debug/libwrapper/mbedtls_x509_get_rsassa_pss_params.o ../.././build/fvp/debug/libwrapper/mbedtls_x509_get_sig_alg.o ../.././build/fvp/debug/libwrapper/mbedtls_md_info_from_type.o ../.././build/fvp/debug/libwrapper/exit.o ../.././build/fvp/debug/libwrapper/atexit.o
> aarch64-none-elf-ld.bfd -o build/fvp/debug/bl1/bl1.elf --fatal-warnings -O1 --gc-sections    -Map=./build/fvp/debug/bl1/bl1.map --script ./build/fvp/debug/bl1/bl1.ld ./build/fvp/debug/bl1/build_message.o ./build/fvp/debug/bl1/smmu_v3.o ./build/fvp/debug/bl1/sp805.o ./build/fvp/debug/bl1/delay_timer.o ./build/fvp/debug/bl1/io_semihosting.o ./build/fvp/debug/bl1/semihosting.o ./build/fvp/debug/bl1/fvp_bl1_setup.o ./build/fvp/debug/bl1/fvp_err.o ./build/fvp/debug/bl1/fvp_io_storage.o ./build/fvp/debug/bl1/cci.o ./build/fvp/debug/bl1/generic_delay_timer.o ./build/fvp/debug/bl1/v2m_flash.o ./build/fvp/debug/bl1/board_arm_trusted_boot.o ./build/fvp/debug/bl1/io_fip.o ./build/fvp/debug/bl1/io_memmap.o ./build/fvp/debug/bl1/io_storage.o ./build/fvp/debug/bl1/arm_bl1_setup.o ./build/fvp/debug/bl1/arm_err.o ./build/fvp/debug/bl1/arm_io_storage.o ./build/fvp/debug/bl1/arm_fconf_io.o ./build/fvp/debug/bl1/fconf.o ./build/fvp/debug/bl1/arm_dyn_cfg.o ./build/fvp/debug/bl1/arm_dyn_cfg_helpers.o ./build/fvp/debug/bl1/fdt_wrappers.o ./build/fvp/debug/bl1/auth_mod.o ./build/fvp/debug/bl1/crypto_mod.o ./build/fvp/debug/bl1/img_parser_mod.o ./build/fvp/debug/bl1/fconf_tbbr_getter.o ./build/fvp/debug/bl1/tbbr_cot.o ./build/fvp/debug/bl1/tbbr_img_desc.o ./build/fvp/debug/bl1/arm_bl1_fwu.o ./build/fvp/debug/bl1/plat_tbbr.o ./build/fvp/debug/bl1/fvp_trusted_boot.o ./build/fvp/debug/bl1/bl1_main.o ./build/fvp/debug/bl1/bl1_arch_setup.o ./build/fvp/debug/bl1/bl1_context_mgmt.o ./build/fvp/debug/bl1/errata_report.o ./build/fvp/debug/bl1/context_mgmt.o ./build/fvp/debug/bl1/plat_bl1_common.o ./build/fvp/debug/bl1/mbedtls_common.o ./build/fvp/debug/bl1/mbedtls_crypto.o ./build/fvp/debug/bl1/mbedtls_x509_parser.o ./build/fvp/debug/bl1/bl1_fwu.o ./build/fvp/debug/bl1/bl_common.o ./build/fvp/debug/bl1/tf_log.o ./build/fvp/debug/bl1/multi_console.o ./build/fvp/debug/bl1/plat_bl_common.o ./build/fvp/debug/bl1/plat_log_common.o ./build/fvp/debug/bl1/plat_common.o ./build/fvp/debug/bl1/popcountdi2.o ./build/fvp/debug/bl1/popcountsi2.o ./build/fvp/debug/bl1/backtrace.o ./build/fvp/debug/bl1/fvp_common.o ./build/fvp/debug/bl1/arm_common.o ./build/fvp/debug/bl1/arm_console.o ./build/fvp/debug/bl1/xlat_tables_arch.o ./build/fvp/debug/bl1/xlat_tables_context.o ./build/fvp/debug/bl1/xlat_tables_core.o ./build/fvp/debug/bl1/xlat_tables_utils.o ./build/fvp/debug/bl1/semihosting_call.o ./build/fvp/debug/bl1/fvp_helpers.o ./build/fvp/debug/bl1/aem_generic.o ./build/fvp/debug/bl1/cortex_a35.o ./build/fvp/debug/bl1/cortex_a53.o ./build/fvp/debug/bl1/cortex_a57.o ./build/fvp/debug/bl1/cortex_a72.o ./build/fvp/debug/bl1/cortex_a73.o ./build/fvp/debug/bl1/arm_dev_rotpk.o ./build/fvp/debug/bl1/bl1_entrypoint.o ./build/fvp/debug/bl1/bl1_exceptions.o ./build/fvp/debug/bl1/cpu_helpers.o ./build/fvp/debug/bl1/platform_up_stack.o ./build/fvp/debug/bl1/dsu_helpers.o ./build/fvp/debug/bl1/context.o ./build/fvp/debug/bl1/debug.o ./build/fvp/debug/bl1/cache_helpers.o ./build/fvp/debug/bl1/misc_helpers.o ./build/fvp/debug/bl1/platform_helpers.o ./build/fvp/debug/bl1/pl011_console.o ./build/fvp/debug/bl1/board_arm_helpers.o ./build/fvp/debug/bl1/arm_helpers.o ./build/fvp/debug/bl1/enable_mmu.o -L./build/fvp/debug/lib -lwrappers -lfdt -lmbedtls -lc 
> aarch64-none-elf-ld.bfd: ./build/fvp/debug/lib/libfdt.a(fdt_ro.o): in function `fdt_getprop_namelen':
> /work/workspace/workspace/tf-worker@7/trusted_firmware/lib/libfdt/fdt_ro.c:385: multiple definition of `fdt_getprop_namelen'; ./build/fvp/debug/lib/libwrappers.a(fdt_getprop_namelen.o):(.text+0x0): first defined here
> aarch64-none-elf-ld.bfd: ./build/fvp/debug/lib/libfdt.a(fdt_ro.o): in function `fdt_node_offset_by_compatible':
> /work/workspace/workspace/tf-worker@7/trusted_firmware/lib/libfdt/fdt_ro.c:752: multiple definition of `fdt_node_offset_by_compatible'; ./build/fvp/debug/lib/libwrappers.a(fdt_node_offset_by_compatible.o):(.text+0x0): first defined here
> aarch64-none-elf-ld.bfd: ./build/fvp/debug/lib/libfdt.a(fdt.o): in function `fdt_check_header':
> /work/workspace/workspace/tf-worker@7/trusted_firmware/lib/libfdt/fdt.c:59: multiple definition of `fdt_check_header'; ./build/fvp/debug/lib/libwrappers.a(fdt_check_header.o):(.text+0x0): first defined here
> Makefile:1035: recipe for target 'build/fvp/debug/bl1/bl1.elf' failed
> make: *** [build/fvp/debug/bl1/bl1.elf] Error 1

I am a bit puzzled about this one, looks like we provide some functions in libfdt/fdt_ro.c, but also have them in libwrappers. Don't understand what the latter is supposed to be and how to fix this.

Patch-set: 3
Reviewer: Gerrit User 1000118 <1000118@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>