Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4: Verified-1
> > 
> > Build Failed 
> > 
> > https://jenkins.oss.arm.com/job/tf-gerrit-tforg-l1/2965/ : This Jenkins server is not publicly accessible. A core maintainer will let you know if this CI failure is blocking the merge of this patch.
> 
> ****** Order of includes on the last patch(es) ******
> 
> Result : FAILURE
> 
> Checking files modified between patches origin/master and HEAD...
> 86f44eeb3:plat/nvidia/tegra/include/drivers/memctrl_v2.h: ['lib/mmio.h should be in
>     project group, after system group']
> 
> 6f9627253:plat/nvidia/tegra/soc/t194/drivers/mce/nvg.c: ['assert.h should be in system
>     group, at the top']
> 
> b780f36d7:plat/nvidia/tegra/soc/t194/plat_secondary.c: ['assert.h should be in system
>     group, at the top']
> 
> e2e144939:plat/nvidia/tegra/common/aarch64/tegra_helpers.S: ['Project includes not
>     in order. Include order should be cortex_a57.h, cpu_macros.S']
> 
> plat/nvidia/tegra/include/t186/tegra_mc_def.h:380: ERROR: Macros with multiple statements should be enclosed in a do - while loop
> +#define mc_set_tsa_r_passthrough(client) \
> +	{ \
> +		mmio_write_32(TEGRA_TSA_BASE + TSA_CONFIG_STATIC0_CSR_##client, \
> +			(TSA_CONFIG_STATIC0_CSR_RESET_R & \
> +			 (uint32_t)~TSA_CONFIG_CSW_MEMTYPE_OVERRIDE_MASK) | \
> +			(uint32_t)TSA_CONFIG_CSW_MEMTYPE_OVERRIDE_PASTHRU); \
> +
> 
> plat/nvidia/tegra/include/t186/tegra_mc_def.h:380: WARNING: macros should not use a trailing semicolon
> +#define mc_set_tsa_r_passthrough(client) \
> +	{ \
> +		mmio_write_32(TEGRA_TSA_BASE + TSA_CONFIG_STATIC0_CSR_##client, \
> +			(TSA_CONFIG_STATIC0_CSR_RESET_R & \
> +			 (uint32_t)~TSA_CONFIG_CSW_MEMTYPE_OVERRIDE_MASK) | \
> +			(uint32_t)TSA_CONFIG_CSW_MEMTYPE_OVERRIDE_PASTHRU); \
> +
> [*] Checking style of 'b780f36d72b6155b067c184518b1d6deb6326a03'
> 
> plat/nvidia/tegra/soc/t194/plat_psci_handlers.c:422: WARNING: line over 80 characters
> +				XUSB_PADCTL_HOST_AXI_STREAMID_PF_0) == TEGRA_SID_XUSB_HOST);
> 
> plat/nvidia/tegra/soc/t194/plat_psci_handlers.c:426: WARNING: line over 80 characters
> +				XUSB_PADCTL_HOST_AXI_STREAMID_VF_0) == TEGRA_SID_XUSB_VF0);
> 
> plat/nvidia/tegra/soc/t194/plat_psci_handlers.c:430: WARNING: line over 80 characters
> +				XUSB_PADCTL_HOST_AXI_STREAMID_VF_1) == TEGRA_SID_XUSB_VF1);
> 
> plat/nvidia/tegra/soc/t194/plat_psci_handlers.c:434: WARNING: line over 80 characters
> +				XUSB_PADCTL_HOST_AXI_STREAMID_VF_2) == TEGRA_SID_XUSB_VF2);
> 
> plat/nvidia/tegra/soc/t194/plat_psci_handlers.c:438: WARNING: line over 80 characters
> +				XUSB_PADCTL_HOST_AXI_STREAMID_VF_3) == TEGRA_SID_XUSB_VF3);
> 
> plat/nvidia/tegra/soc/t194/plat_psci_handlers.c:442: WARNING: line over 80 characters
> +				XUSB_PADCTL_DEV_AXI_STREAMID_PF_0) == TEGRA_SID_XUSB_DEV);
> 
> plat/nvidia/tegra/soc/t194/plat_secondary.c:56: WARNING: line over 80 characters
> +	assert(mmio_read_32(TEGRA_MISC_BASE + MISCREG_AA64_RST_LOW) == addr_low);
> 
> plat/nvidia/tegra/soc/t194/plat_secondary.c:58: WARNING: line over 80 characters
> +	assert(mmio_read_32(TEGRA_MISC_BASE + MISCREG_AA64_RST_HIGH) == addr_high);
> 
> plat/nvidia/tegra/soc/t194/plat_secondary.c:63: WARNING: line over 80 characters
> +	assert(mmio_read_32(TEGRA_SCRATCH_BASE + SCRATCH_RESET_VECTOR_LO) == addr_low);
> 
> plat/nvidia/tegra/soc/t194/plat_secondary.c:66: WARNING: line over 80 characters
> +	assert(mmio_read_32(TEGRA_SCRATCH_BASE + SCRATCH_RESET_VECTOR_HI) == addr_high);
> 
> plat/nvidia/tegra/soc/t194/plat_secondary.c:69: WARNING: line over 80 characters
> +	assert(mmio_read_32(TEGRA_SCRATCH_BASE + SECURE_SCRATCH_RSV72_LO) == (uint32_t)tzdram_addr);
> 
> plat/nvidia/tegra/soc/t194/plat_secondary.c:72: WARNING: line over 80 characters
> +	assert(mmio_read_32(TEGRA_SCRATCH_BASE + SECURE_SCRATCH_RSV72_HI) == (uint32_t)src_len_bytes);
> 
> plat/nvidia/tegra/soc/t194/plat_setup.c:299: WARNING: line over 80 characters
> +			XUSB_PADCTL_HOST_AXI_STREAMID_PF_0) == TEGRA_SID_XUSB_HOST);
> 
> plat/nvidia/tegra/soc/t194/plat_setup.c:303: WARNING: line over 80 characters
> +			XUSB_PADCTL_HOST_AXI_STREAMID_VF_0) == TEGRA_SID_XUSB_VF0);
> 
> plat/nvidia/tegra/soc/t194/plat_setup.c:307: WARNING: line over 80 characters
> +			XUSB_PADCTL_HOST_AXI_STREAMID_VF_1) == TEGRA_SID_XUSB_VF1);
> 
> plat/nvidia/tegra/soc/t194/plat_setup.c:311: WARNING: line over 80 characters
> +			XUSB_PADCTL_HOST_AXI_STREAMID_VF_2) == TEGRA_SID_XUSB_VF2);
> 
> plat/nvidia/tegra/soc/t194/plat_setup.c:315: WARNING: line over 80 characters
> +			XUSB_PADCTL_HOST_AXI_STREAMID_VF_3) == TEGRA_SID_XUSB_VF3);
> 
> plat/nvidia/tegra/soc/t194/plat_setup.c:319: WARNING: line over 80 characters
> +			XUSB_PADCTL_DEV_AXI_STREAMID_PF_0) == TEGRA_SID_XUSB_DEV);

The following is a false positive. lib/mmio.h has been removed in this change.

86f44eeb3:plat/nvidia/tegra/include/drivers/memctrl_v2.h: ['lib/mmio.h should be in
    project group, after system group']

Patch-set: 4
Reviewer: Gerrit User 1000162 <1000162@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>