Update patch set 1
Patch Set 1:

> Patch Set 1: Verified-1
> 
> Build Failed 
> 
> https://jenkins.oss.arm.com/job/tf-gerrit-tforg-l1/3335/ : This Jenkins server is not publicly accessible. A core maintainer will let you know if this CI failure is blocking the merge of this patch.


Can you please first rebase the patchset (or this single change)?

There is an earlier change in the series breaking the platform builds:

09:42:20 lib/psci/psci_suspend.c:21:10: fatal error: plat_pm.h: No such file or directory
09:42:20    21 | #include <plat_pm.h>

Patch-set: 1
Reviewer: Gerrit User 1000228 <1000228@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>