fix(stm32mp1): add missing assert.h include
There is a compilation error if flag STM32MP_USE_STM32IMAGE is enabled:
plat/st/stm32mp1/plat_image_load.c: In function
 'plat_get_bl_image_load_info':
plat/st/stm32mp1/plat_image_load.c:30:2: error: implicit declaration of
 function 'assert' [-Werror=implicit-function-declaration]
   30 |  assert(bl33 != NULL);
      |  ^~~~~~
plat/st/stm32mp1/plat_image_load.c:9:1: note: 'assert' is defined in
 header '<assert.h>'; did you forget to '#include <assert.h>'?
    8 | #include <plat/common/platform.h>
  +++ |+#include <assert.h>
    9 |

Signed-off-by: Yann Gautier <yann.gautier@st.com>
Change-Id: I9d97d7d9677816ebea455c8c338caf254dc733df