Update patch set 1
Patch Set 1:

Failed with the following error:
plat/nvidia/tegra/soc/t194/plat_memctrl.c -o build/tegra/t194/debug/bl31/plat_memctrl.o
plat/nvidia/tegra/soc/t194/plat_memctrl.c:11:10: fatal error: tegra_mc_def.h: No such file or directory
 #include <tegra_mc_def.h>
          ^~~~~~~~~~~~~~~~

header file is added in next patch, will update it to +1 if subsequent patch is success

Patch-set: 1