Update patch set 2
Patch Set 2:

The CI system has identified this change has broken a number(around 60ish) of other platform/component builds where various errors of the following form have been reported (I've not checked them all):

Example:
drivers/delay_timer/generic_delay_timer.c:18: error: "MHZ_TICKS_PER_SEC" redefined [-Werror]
   18 | #define MHZ_TICKS_PER_SEC 1000000
      | 
In file included from include/common/debug.h:10,
                 from include/lib/libc/assert.h:14,
                 from drivers/delay_timer/generic_delay_timer.c:7:
include/lib/utils_def.h:164: note: this is the location of the previous definition
  164 | #define MHZ_TICKS_PER_SEC U(1000000)
      | 
cc1: all warnings being treated as errors

I'm hoping the fix will be straightforward on searching the TF-A code base for the MHZ_TICKS_PER_SEC defines and removing the offending redefine as part of this patch. Once done we can redo the CI checking.

We are close to having the first part of the OpenCI system deployed on trustedfirmware.org servers so that partners can see for themselves directly the impact of their patch submissions on the CI system when they submit patches for review.

Patch-set: 2
Reviewer: Gerrit User 1000049 <1000049@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>