Update patch set 1
Patch Set 1:

Regarding the CI failure, it looks like the new call to zynqmp_ipi_config_table_init() on line 330 of zynqmp_common.c is causing a compilation failure when built by our CI. Here is the relevant log output (I have removed some internal paths):

> 10:34:57 aarch64-linux-gnu-ld.bfd: ./build/zynqmp/debug/bl32/zynqmp_common.o: in function `zynqmp_config_setup':

> 10:34:57 <path removed>/plat/xilinx/zynqmp/aarch64/zynqmp_common.c:330: undefined reference to `zynqmp_ipi_config_table_init'

> 10:34:57 <path removed>/plat/xilinx/zynqmp/aarch64/zynqmp_common.c:330:(.text.zynqmp_config_setup+0x18): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `zynqmp_ipi_config_table_init'

> 10:34:57 Makefile:810: recipe for target 'build/zynqmp/debug/bl32/bl32.elf' failed

Patch-set: 1