Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> Pankaj,
> 
> I do fear we have run out of time in getting these patches reviewed for inclusion in the release. Although we have been working with you to get the CI passing for the patch stack most of the patches don't have any reviews. For a large patchstack like this we need more than 4 days especially when we are closing in on the freeze date tomorrow and we have a number of patches ahead of yours. If we do miss the freeze date we will work with you to get the patchstack ready for submission when the tree reopens mid April.
> 
> Joanna

Hi Joana,

These errors are coming to me as well. But it was last discussed that if these error comes again, it will be ignored.


Set #1
------
drivers/nxp/fsl_sec/src/fsl_sec.c:282: ERROR: memset to 0's uses 0 as the 2nd argument, not the 3rd
+	memset(rand_byte, 64, 0);

[Pangupta] This should not be treated as error as the memset is defined as follows:

			include/lib/libc/string.h:void *memset(void *dst, int val, size_t count);

Set #2
------
drivers/nxp/ddr/nxp-ddr/utility.c:114: ERROR: space prohibited after that '&' (ctx:WxW)
+		disable_ddrc = !(valid_spd_mask & 0x1) ? 1 :
 		                                ^
drivers/nxp/ddr/nxp-ddr/utility.c:115: ERROR: space prohibited after that '&' (ctx:WxW)
+				!(valid_spd_mask & 0x2) ? 2 : 0;
 				                 ^
drivers/nxp/ddr/nxp-ddr/utility.c:118: ERROR: space prohibited after that '&' (ctx:WxW)
+		disable_ddrc = !(valid_spd_mask & 0x1) ? 1 :
 		                                ^
drivers/nxp/ddr/nxp-ddr/utility.c:119: ERROR: space prohibited after that '&' (ctx:WxW)
+				!(valid_spd_mask & 0x4) ? 2 : 0;
 				                 ^
...
drivers/nxp/ddr/phy-gen2/phy.c:1443: ERROR: space prohibited after that '&' (ctx:WxW)
+	if ((index & 0xffff) > MAX_ARGS)	/* up to MAX_ARGS args so far */
 	           ^
drivers/nxp/ddr/phy-gen2/phy.c:1445: ERROR: space prohibited after that '&' (ctx:WxW)
+	for (i = 0; i < (index & 0xffff) && i < MAX_ARGS; i++)

[Pangupta] These error should also be ignored. This was already agreed previously.


Set #3
------

Checking files modified between patches origin/master and HEAD...
1bf8ed351:tools/nxp/byte_swap.c: ['stdint.h should be in system group, at the top',
  'stdio.h should be in system group, at the top', 'stdlib.h should be in system group,
    at the top', 'string.h should be in system group, at the top']
1bf8ed351:tools/nxp/create_pbl.c: ['stdbool.h should be in system group, at the top',
  'stdint.h should be in system group, at the top', 'stdio.h should be in system group,
    at the top', 'stdlib.h should be in system group, at the top', 'string.h should
    be in system group, at the top']



[Pangupta] These error should also be ignored as well: 
Order of libc header files alphabetically:

#include <getopt.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

There cannot be any other order to this. This error to be removed.

Patch-set: 3
Reviewer: Gerrit User 1000209 <1000209@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>