fix(build): fix LD option detection when gcc wrapper (LTO) is used
When LD is defined as gcc and -nostdlib is missing, then
it complains about undefined references.

```
$ aarch64-none-elf-gcc -Wl,--no-warn-rwx-segments -v
...
crt0.o: in function `_mainCRTStartup':
undefined reference to `main'

libc.a(libc_a-writer.o): in function `_write_r':
undefined reference to `_write'

libc.a(libc_a-closer.o): in function `_close_r':
undefined reference to `_close'

libc.a(libc_a-lseekr.o): in function `_lseek_r':
undefined reference to `_lseek'

libc.a(libc_a-readr.o): in function `_read_r':
undefined reference to `_read'

libc.a(libc_a-sbrkr.o): in function `_sbrk_r':
undefined reference to `_sbrk'
```

To avoid complain about missing input files /dev/null is used as input file.
```
$ aarch64-none-elf-gcc -nostdlib -Wl,--no-warn-rwx-segments -v
aarch64-none-elf/bin/ld: no input files
```

Tested with aarch64-none-elf-gcc (Arm GNU Toolchain 12.3.Rel1 (Build arm-12.35)) 12.3.1 20230626.

Change-Id: Ifa30c6a71d6a82c5a977aa672ae58870cf9ec0d2
Signed-off-by: Andrey Skvortsov <andrej.skvortzov@gmail.com>