Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > Patch Set 5: Verified-1
> > 
> > Build Failed 
> > 
> > https://jenkins.oss.arm.com/job/tf-gerrit-tforg-l1/2156/ : This Jenkins server is not publicly accessible. A core maintainer will let you know if this CI failure is blocking the merge of this patch.
> 
> aarch64-none-elf-ld.bfd: ./build/fvp/debug/lib/libfdt.a(fdt_ro.o): in function `fdt_getprop_namelen':
> /work/workspace/workspace/tf-worker@8/trusted_firmware/lib/libfdt/fdt_ro.c:385: multiple definition of `fdt_getprop_namelen'; ./build/fvp/debug/lib/libwrappers.a(fdt_getprop_namelen.o):(.text+0x0): first defined here
> aarch64-none-elf-ld.bfd: ./build/fvp/debug/lib/libfdt.a(fdt_ro.o): in function `fdt_node_offset_by_compatible':
> /work/workspace/workspace/tf-worker@8/trusted_firmware/lib/libfdt/fdt_ro.c:752: multiple definition of `fdt_node_offset_by_compatible'; ./build/fvp/debug/lib/libwrappers.a(fdt_node_offset_by_compatible.o):(.text+0x0): first defined here
> aarch64-none-elf-ld.bfd: ./build/fvp/debug/lib/libfdt.a(fdt.o): in function `fdt_check_header':
> /work/workspace/workspace/tf-worker@8/trusted_firmware/lib/libfdt/fdt.c:59: multiple definition of `fdt_check_header'; ./build/fvp/debug/lib/libwrappers.a(fdt_check_header.o):(.text+0x0): first defined here
> Makefile:1045: recipe for target 'build/fvp/debug/bl1/bl1.elf' failed
> make: *** [build/fvp/debug/bl1/bl1.elf] Error 1

Mmmh, too bad, I was hoping that adding that function to jmptable.i would fix. Does anybody know what causes this issue?
I am somewhat clueless about this whole romlib and libwrappers.a.

Patch-set: 5
Reviewer: Gerrit User 1000118 <1000118@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>