Update patch set 6
Patch Set 6:

> Patch Set 5:
> 
> > Patch Set 4:
> > 
> > > Patch Set 4: Code-Review-1
> > > 
> > > > Patch Set 4:
> > > > 
> > > > Looks like the default value is also used for ECDSA. This is a build failure from one of the configs (tftf-l2-fwu/fvp-tspd-tbb-mbedtls-ecdsa-dualroot,fvp-fwu:fvp-tftf.fwu-aemv8a)
> > > > 
> > > > NOTICE:  CoT Generation Tool: Built : 14:42:56, Jul 17 2020
> > > > NOTICE:  Target platform: Dual root of trust
> > > > ERROR:   '2048' is not a valid key size for 'ecdsa'
> > > > NOTICE:  Valid sizes are: 
> > > > Makefile:1211: recipe for target 'certificates' failed
> > > > make: *** [certificates] Error 1
> > > > make: Leaving directory '/work/workspace/workspace/tf-worker@10/trusted_firmware'
> > 
> > Hi Zelalem/Joanna
> > 
> > I am not able to reproduce this problem 'manually', alias using just make with params
> > 
> > MBEDTLS_DIR=<path to mbedtls 2.18.0>  make  -e ARM_ROTPK_LOCATION=devel_ecdsa COT=dualroot CROSS_COMPILE=aarch64-none-elf- ENABLE_ASSERTIONS=0 GENERATE_COT=1 KEY_ALG=ecdsa PLAT=fvp ROT_KEY=plat/arm/board/common/rotpk/arm_rotprivk_ecdsa.pem SPD=tspd TF_MBEDTLS_KEY_ALG=rsa+ecdsa TRUSTED_BOARD_BOOT=1  DEBUG=1 V=1 fiptool all
> > 
> > I tested on master and on this patchset branch: same result, no invalid side issue. 
> > 
> > 
> > However, when trying to reproduce it through the tf-a-ci-scripts project with the indicated test-group, I ran into this issue:
> > 
> > ----
> > aarch64-none-elf-gcc -g -DDEBUG=1 -DENABLE_BACKTRACE=1 -DTSP_INIT_ASYNC=0 -DTSP_NS_INTR_ASYNC_PREEMPT=0 -DFVP_USE_SP804_TIMER=0 -DFVP_USE_GIC_DRIVER=FVP_GICV3 -DFVP_CLUSTER_COUNT=2 -DFVP_MAX_CPUS_PER_CLUSTER=4 -DFVP_MAX_PE_PER_CPU=1 -DFVP_INTERCONNECT_DRIVER=FVP_CCI -DGICV3_SUPPORT_GIC600=1 -DGIC_ENABLE_V4_EXTN=0 -DGIC_EXT_INTID=0 -DPLAT_EXTRA_LD_SCRIPT -DARM_ROTPK_HASH='"plat/arm/board/common/rotpk/arm_rotpk_ecdsa_sha256.bin"' -DARM_ROTPK_LOCATION_ID=ARM_ROTPK_DEVEL_ECDSA_ID -DARM_COT_dualroot -DARM_PROTPK_HASH='"plat/arm/board/common/protpk/arm_protpk_rsa_sha256.bin"' -DARM_BL31_IN_DRAM=0 -DARM_TSP_RAM_LOCATION_ID=ARM_DRAM_ID -DARM_RECOM_STATE_ID_ENC=0 -DARM_DISABLE_TRUSTED_WDOG=0 -DARM_CONFIG_CNTACR=1 -DARM_BL31_IN_DRAM=0 -DARM_PLAT_MT=0 -DARM_XLAT_TABLES_LIB_V1=0 -DARM_LINUX_KERNEL_AS_BL33=0 -DMBEDTLS_SHA256_SMALLER -DARM_CRYPTOCELL_INTEG=0 -DXLAT_TABLES_LIB_V2=1 -DMBEDTLS_CONFIG_FILE="<drivers/auth/mbedtls/mbedtls_config.h>" -DTF_MBEDTLS_KEY_ALG_ID=TF_MBEDTLS_RSA_AND_ECDSA -DTF_MBEDTLS_KEY_SIZE=2048 -DTF_MBEDTLS_HASH_ALG_ID=TF_MBEDTLS_SHA256 -DTF_MBEDTLS_USE_AES_GCM=0 -DA57_ENABLE_NONCACHEABLE_LOAD_FWD=0 -DSKIP_A57_L1_FLUSH_PWR_DWN=0 -DA53_DISABLE_NON_TEMPORAL_HINT=1 -DA57_DISABLE_NON_TEMPORAL_HINT=1 -DWORKAROUND_CVE_2017_5715=1 -DWORKAROUND_CVE_2018_3639=1 -DDYNAMIC_WORKAROUND_CVE_2018_3639=1 -DNEOVERSE_N1_EXTERNAL_LLC=0 -DERRATA_A9_794073=0 -DERRATA_A15_816470=0 -DERRATA_A15_827671=0 -DERRATA_A17_852421=0 -DERRATA_A17_852423=0 -DERRATA_A35_855472=0 -DERRATA_A53_819472=0 -DERRATA_A53_824069=0 -DERRATA_A53_826319=0 -DERRATA_A53_827319=0 -DERRATA_A53_835769=0 -DERRATA_A53_836870=0 -DERRATA_A53_843419=0 -DERRATA_A53_855873=0 -DERRATA_A55_768277=0 -DERRATA_A55_778703=0 -DERRATA_A55_798797=0 -DERRATA_A55_846532=0 -DERRATA_A55_903758=0 -DERRATA_A55_1221012=0 -DERRATA_A57_806969=0 -DERRATA_A57_813419=0 -DERRATA_A57_813420=0 -DERRATA_A57_814670=0 -DERRATA_A57_817169=0 -DERRATA_A57_826974=0 -DERRATA_A57_826977=0 -DERRATA_A57_828024=0 -DERRATA_A57_829520=0 -DERRATA_A57_833471=0 -DERRATA_A57_859972=0 -DERRATA_A72_859971=0 -DERRATA_A73_852427=0 -DERRATA_A73_855423=0 -DERRATA_A75_764081=0 -DERRATA_A75_790748=0 -DERRATA_A76_1073348=0 -DERRATA_A76_1130799=0 -DERRATA_A76_1220197=0 -DERRATA_A76_1257314=0 -DERRATA_A76_1262606=0 -DERRATA_A76_1262888=0 -DERRATA_A76_1275112=0 -DERRATA_A76_1286807=0 -DERRATA_A76_1791580=0 -DERRATA_A76_1800710=0 -DERRATA_A77_1800714=0 -DERRATA_A78_1688305=0 -DERRATA_N1_1043202=0 -DERRATA_N1_1073348=0 -DERRATA_N1_1130799=0 -DERRATA_N1_1165347=0 -DERRATA_N1_1207823=0 -DERRATA_N1_1220197=0 -DERRATA_N1_1257314=0 -DERRATA_N1_1262606=0 -DERRATA_N1_1262888=0 -DERRATA_N1_1275112=0 -DERRATA_N1_1315703=0 -DERRATA_N1_1542419=0 -DERRATA_DSU_798953=0 -DERRATA_DSU_936184=0 -DSTACK_PROTECTOR_ENABLED=0 -DCRASH_REPORTING=1 -DEL3_EXCEPTION_HANDLING=0 -DSDEI_SUPPORT=0 -DALLOW_RO_XLAT_TABLES=0 -DARM_ARCH_MAJOR=8 -DARM_ARCH_MINOR=0 -DCOLD_BOOT_SINGLE_CPU=0 -DCTX_INCLUDE_AARCH32_REGS=1 -DCTX_INCLUDE_FPREGS=0 -DCTX_INCLUDE_PAUTH_REGS=0 -DEL3_EXCEPTION_HANDLING=0 -DCTX_INCLUDE_MTE_REGS=0 -DCTX_INCLUDE_EL2_REGS=0 -DDECRYPTION_SUPPORT_none -DENABLE_AMU=1 -DENABLE_ASSERTIONS=0 -DENABLE_BTI=0 -DENABLE_MPAM_FOR_LOWER_ELS=0 -DENABLE_PAUTH=0 -DENABLE_PIE=0 -DENABLE_PMF=1 -DENABLE_PSCI_STAT=1 -DENABLE_RUNTIME_INSTRUMENTATION=0 -DENABLE_SPE_FOR_LOWER_ELS=1 -DENABLE_SVE_FOR_NS=1 -DENCRYPT_BL31=0 -DENCRYPT_BL32=0 -DERROR_DEPRECATED=0 -DFAULT_INJECTION_SUPPORT=0 -DGICV2_G0_FOR_EL3=0 -DHANDLE_EA_EL3_FIRST=0 -DHW_ASSISTED_COHERENCY=0 -DLOG_LEVEL=40 -DMEASURED_BOOT=0 -DNS_TIMER_SWITCH=0 -DPL011_GENERIC_UART=0 -DPLAT_fvp -DPROGRAMMABLE_RESET_ADDRESS=0 -DPSCI_EXTENDED_STATE_ID=0 -DRAS_EXTENSION=0 -DRESET_TO_BL31=0 -DSEPARATE_CODE_AND_RODATA=1 -DSEPARATE_NOBITS_REGION=0 -DRECLAIM_INIT_CODE=1 -DSPD_tspd -DSPIN_ON_BL1_EXIT=0 -DSPM_MM=0 -DSPMD_SPM_AT_SEL2=1 -DTRUSTED_BOARD_BOOT=1 -DUSE_COHERENT_MEM=1 -DUSE_DEBUGFS=0 -DARM_IO_IN_DTB=0 -DSDEI_IN_FCONF=0 -DSEC_INT_DESC_IN_FCONF=0 -DUSE_ROMLIB=0 -DUSE_TBBR_DEFS=1 -DWARMBOOT_ENABLE_DCACHE_EARLY=0 -DBL2_AT_EL3=0 -DBL2_IN_XIP_MEM=0 -DBL2_INV_DCACHE=1 -DUSE_SPINLOCK_CAS=0 -DERRATA_SPECULATIVE_AT=0 -DRAS_TRAP_LOWER_EL_ERR_ACCESS=0 -DCOT_DESC_IN_DTB=0 -DDYN_DISABLE_AUTH=1 -DAARCH64 -Iinclude -Iinclude/arch/aarch64 -Iinclude/lib/cpus/aarch64 -Iinclude/lib/el3_runtime/aarch64 -Iplat/arm/board/fvp/include -Iinclude/plat/arm/common/aarch64 -Iinclude/bl32/tsp -Iinclude/bl32/tsp -Iinclude/lib/libfdt -Iinclude/lib/libc -Iinclude/lib/libc/aarch64  -I/ext/repos/tf-a-job-local/workspace/ws/mbedtls/include -nostdinc -Werror -Wall -Wmissing-include-dirs -Wunused -Wdisabled-optimization	-Wvla -Wshadow -Wno-unused-parameter -Wredundant-decls -Wunused-but-set-variable -Wmaybe-uninitialized -Wpacked-bitfield-compat -Wshift-overflow=2 -Wlogical-op -Wno-error=deprecated-declarations -Wno-error=cpp -march=armv8-a -mgeneral-regs-only -mstrict-align -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -fno-common -Os -std=gnu99 -fno-omit-frame-pointer -fno-stack-protector  -Wp,-MD,/ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/fvp/debug/libfdt/fdt.d -MT /ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/fvp/debug/libfdt/fdt.o -MP -c lib/libfdt/fdt.c -o /ext/repos/tf-a-job-local/workspace/trusted-firmware-a/build/fvp/debug/libfdt/fdt.o
> > cc1: error: /ext/repos/tf-a-job-local/workspace/ws/mbedtls/include: No such file or directory [-Werror=missing-include-dirs]
> > cc1: all warnings being treated as errors
> > ----
> > 
> > so there may be an logic problem placing correct include (-I) directory for mbedtls.
> 
> 
> 
> Hi Leonardo,
> 
> On the initial reason for the build failure I guess you'd need to enclose the default key size setting like this:
> 
> ifeq (${KEY_ALG},rsa)
> KEY_SIZE			:= 2048
> endif
> 
> The doc mentions the default key size is 2048 for RSA, but unspecified for ECDSA.
> 
> For the build failure you get with tf-a-ci-scripts, we're checking internally what the status of it.
> 
> Regards,
> Olivier.

Hi @Leonardo the latest patch doesn't fix the original issue due the reason Olivier mentioned above. You might want to do what Olivier suggested.

Patch-set: 6
Reviewer: Gerrit User 1000219 <1000219@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>