Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review-1
> 
> EHF is meant to support SErrors as well.

Actually EHF and RAS do not play well together. This is what I see without this change

lib/extensions/ras/ras_common.c:18:3: error: #error Platform must define RAS priority value
   18 | # error Platform must define RAS priority value
      |   ^~~~~
lib/extensions/ras/ras_common.c: In function 'ras_init':
lib/extensions/ras/ras_common.c:141:32: error: 'PLAT_RAS_PRI' undeclared (first use in this function)
  141 |  ehf_register_priority_handler(PLAT_RAS_PRI, ras_interrupt_handler);
      |                                ^~~~~~~~~~~~
lib/extensions/ras/ras_common.c:141:32: note: each undeclared identifier is reported only once for each function it appears in
  CC      lib/extensions/spe/spe.c
  CC      lib/locks/bakery/bakery_lock_normal.c
Makefile:1019: recipe for target 'build/tegra/t194/release/bl31/ras_common.o' failed
make: *** [build/tegra/t194/release/bl31/ras_common.o] Error 1
make: *** Waiting for unfinished jobs....

This means RAS expects interrupts to handle RAS errors. For Tegra194 we do not use any interrupts for uncorrectable errors - we use SERRs instead.

Patch-set: 1
Reviewer: Gerrit User 1000162 <1000162@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>