Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > > Patch Set 1: Verified-1
> > > > 
> > > > Build Failed 
> > > > 
> > > > https://jenkins.oss.arm.com/job/tf-gerrit-tforg-l1/3340/ : This Jenkins server is not publicly accessible. A core maintainer will let you know if this CI failure is blocking the merge of this patch.
> > > 
> > > Madhukar, why it failed?
> > 
> > ****** Copyright headers of files modified by this patch ******
> > 
> > Result : FAILURE
> > 
> > Checking the copyrights in the code...
> > Checking files modified between patches 271708e06462a13eb163efc61ed1fe82a002192c and HEAD...
> > WARNING: Copyright is out of date in plat/marvell/armada/a3k/common/a3700_common.mk: '# Copyright (C) 2018 Marvell International Ltd.'
> > WARNING: Copyright is out of date in plat/marvell/armada/common/marvell_common.mk: '# Copyright (C) 2018 Marvell International Ltd.'
> > ERROR: Missing copyright in plat/marvell/version.mk
> > ERROR: License ID error in plat/marvell/version.mk
> > 
> > Summary:
> > 	4 files analyzed
> > 	1 errors found
> 
> But what is the problem? I have not modified any copyright.

We expect every source file in TF-A to have copyright, license header. Since version.mk doesnt have the header, our CI check fails. Any idea why the header is missing? Can you add it?

Patch-set: 1
Reviewer: Gerrit User 1000098 <1000098@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>